### PR TITLE
Add r4i rev4/5

### PR DESCRIPTION
**Pull request by d3m3vilurr**
Apply zoogie's patch to r4igold3ds #77 

not tested.

### CODE REVIEW

**Comment by kitling** [comment]
I'd prefer the two encryption types be merged into the same function, (if statement switch) and detecting based on flashchip being zero seems iffy when this is our only method of detection and I suspect other carts will have this naturally.

Other than than, LGTM. I'd like to hear if @zoogie has any comments, though.

**Comment by zoogie** [comment]
Backup, restore, and ntrboot inject worked in my test on rev5. Nice job @d3m3vilurr !

The only small suggestion I would make is some feedback as to which type of card flashing technique is being used. The user should also be warned that a rev6 or rev7 will not work with this, even though the app will likely detect it as rev5-6 (6-7 also have hw_revision = 0). Otherwise, LGTM.

**Comment by kitling** [comment]
So, we could add it to the description. "This will not work on revision 6-7 even though it detects as working!"

I really wish we had a way to display a subset of the log on-screen, so we could have alerts like that.

hm. I could make alert pop open a dialog on the screen whenever it happens...

**Comment by kitling** [comment]
@zoogie how does that look?

**Comment by zoogie** [comment]
Looks perfect, Kitling.

**Comment by d3m3vilurr** [comment]
@zoogie @kitling do you know each cart's c7 command results?

**Comment by kitling** [comment]
LGTM! We can take a look at the C7 values across multiple carts after this is merged, I guess.

**Pull request merged**
