### PR TITLE
Device interface refactor, remove device/platform specific stuff and DSTT implementation.

### PR DESCRIPTION
**Pull request by HandsomeMatt**
To go with these changes: https://github.com/kitling/ntrboot_flasher/pull/34

### CODE REVIEW

**Comment by Valeri0p** [comment]
Very good to see :D
But didn't @tuxsh start the refactoring some days ago?
https://github.com/kitling/flashcart_core/commits/refactor
Dunno if it's your same style...

**Comment by Raugo** [comment]
I tried your branch on one of my DSTTs, the read process work well but the write no, after the process 3DS don't start with the flash inside and a after make a new dump of the flash the content is only 

10 11 12 12 20 21 22 23 30 31 32 33 40 41 42 43 and after that all FF

**Comment by HandsomeMatt** [comment]
@Raugo do you just run any WIP code without reading it? DSTT result was as expected, it's just a test of the flash commands.

**Comment by HandsomeMatt** [comment]
Latest commit can now restore and inject ntrboot on the DSTT. Can also unbrick your DSTT if you restore from someone elses flash.

So far it only supports the specific flash chip: MACRONIX MX29LV400B (which appears to be the most common.) If you don't have that flash chip, the flashcart initalize will fail.

Todo on the DSTT:
* Add support for other flash chips that use the same commands as the Macronix, blocks are arranged differently per flashchip so need different erasing addresses & lengths.
* Add support for other flash chips that use completely different flashcart commands to the Macronix - there is a different erase and write command for these.
* writeFlash currently assumes you're going to write to the entire flash and erases every block - mainly because I'm not smart enough to write C++ that can deal with all the different blocks.

**Comment by annson24** [comment]
Two of my three DSTTs have flashchips of SPANSION MBM29LV400BC. The other one is ST M29W400B. Sooo apparently, your chip isnt very famous from here.

**Comment by Raugo** [comment]
HandsomeMatt I didnt see that message but I knew it was not a release and anything can happen, I only tried it for test, I have two and really dont use it. The flashchip is ESI ES29LV400DB

**Comment by HandsomeMatt** [comment]
I have another commit in works for various other flash chips but I also
have work today, so no push till later.

On 31 Aug 2017 1:02 pm, "Raugo" <notifications@github.com> wrote:

HandsomeMatt I didnt see that message but I knew it was not a release and
anything can happen, I only tried it for test, I have two and really dont
use it. The flashchip is ESI ES29LV400DB

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/kitling/flashcart_core/pull/43#issuecomment-326274694>,
or mute the thread

**Comment by HandsomeMatt** [comment]
DSTT:

I added 24 more flash chips to support (they use the identical erase & program commands as each other, however they differ in block sectors that require erasing. The most common boot block sector layout is: `16K, 8K, 8K, 32K, 64K`, some only use a a single block, etc..

The rest of the known flash chips require different write commands as specified in their data sheets, these flash chips are:
```    0x912C: http://pdf.datasheetcatalog.com/datasheet/micron/MT28F160A3.pdf (8x4K-Word Blocks) (RA: X:0xFF) (PW: X:0x10/40 & WA:PD) (ER: X:0x20 & BA:0xD0)
    0x922C: http://www.dataman.com/media/datasheet/Micron/mt28f160c3_3.pdf (8x4K-Word Blocks) (similar/same to above)
    0x9320: http://pdf.datasheetcatalog.com/datasheet/stmicroelectronics/7585.pdf (8x4K-Word Blocks) (^)   ```

There are also the following flash chips I couldn't find data sheets for:
```    0x49B0: SHARP LH28F160BGHB-BTL (can't find datasheet)
    0x9020: ST M28W160(B)T (can't find datasheet)
    0x9089: INTEL 28F160B3T (can't find specific datasheet)
    0x9120: ST M28W160(B)B (can't find datasheet)
    0x9189: INTEL 28F160B3B (can't find specific datasheet)
    0x9289: INTEL 28F800B3T (can't find specific datasheet)
    0x9389: INTEL 28F800B3B (can't find specific datasheet)
    0x9689: INTEL 28F320B3T (can't find specific datasheet)
    0x9789: INTEL 28F320B3B (can't find specific datasheet)```

**Comment by Raugo** [comment]
Tested and work well, ntrboot installed and working and also I restored my previous backup and the flashcart works again. Thanks

**Comment by annson24** [comment]
Also tested, I can backup, restore, inject on my SPANSION MBM29LV400BC however, ntrboot doesn't work with it. On my ST M29W400B on the other hand, I couldn't restore the backup properly, it restores but it stays bricked. One person also reported that his ak2i (small chip) now doesn't work after using the build with this latest commit.

Hope this test report helps.

**Comment by HandsomeMatt** [comment]
Brilliant @Raugo, thanks for testing.

@annson the ak2i implementations are stubbed so they literally do nothing in this commit, no reads and no writes so I don't think he bricked his card from this, please stop running random code on other people's devices that says [WIP] without fully reading it first. As for the DSTT the intended use isn't really to restore functionality to your previously bricked DSTTs.

**Comment by Alexlr94** [comment]
@HandsomeMatt then is it possible to implement this to work with a DS instead of a modded 3DS, I mean, to generate a .nds capable of flashing the DSTT. Thanks for your work mate

**Comment by annson24** [comment]
Sorry for the misinformation, my ST M29W400B wasn't bricked before. I referred to it as bricked after installing ntrboot with this commit because all its functionality was gone and ntrboot wasn't working too. I tried restoring the backup I made (also with this commit) but fuctionalities were still missing.

Regarding ak2i, I wasn't the one who tested that but will gladly tell the person who did about that info.

Anyway, thanks for your hard work.

**Comment by angelsl** [comment]
@Alexlr94 

>then is it possible to implement this to work with a DS instead of a modded 3DS, I mean, to generate a .nds capable of flashing the DSTT. Thanks for your work mate

[It's already been done.](https://github.com/d3m3vilurr/ak2i_ntrcardhax_flasher)

**Comment by Alexlr94** [comment]
@angelsl but that's not compatible with all the chips avaiable now with the @HandsomeMatt ntrboot_flasher

**Comment by HandsomeMatt** [comment]
Wait for this to be finished.

**Comment by d3m3vilurr** [comment]
@Alexlr94 It's complicated. current status, this PR lost original feature(ak2i & r4i things)
so wait to finish @HandsomeMatt 's refactoring.

**Comment by angelsl** [comment]
@Alexlr94 

> but that's not compatible with all the chips avaiable now with the @HandsomeMatt ntrboot_flasher

You can update it. It uses this library (flashcart_core).

**Comment by SaikoPikachuu** [comment]
will this support r4 sdhc dual core 2016? sorry idk much about coding and stuff._. just wanna unbricm my 3ds...

**Comment by WhoIsCo** [comment]
@HandsomeMatt, can you look at ATMEL AT49BV1614T, please? Maybe it's not too hard to add this chip's support. Photo can be found here:

https://s26.postimg.org/5kdhcufx5/WP_20170831_22_41_06_Pro_2.jpg

**Comment by DiamondMinerITA** [comment]
Can you add the SPANSION S19GL032ATFA0060?

**Comment by Siogenon** [comment]
Thank's.

Supercard ds onei mini is like supercard ds two no ?

**Comment by kitling** [comment]
Guys. This is not the place for "can you support xyz".

**Comment by DiamondMinerITA** [comment]
Soooooooo, how we tell him what chips exist?
Shall we send the datasheet too?

**Comment by HandsomeMatt** [comment]
I'll accept requests for different DSTT implementations in a seperate pull request after I finish this one.

**Comment by DiamondMinerITA** [comment]
Ooooh, ok.
What do you need to finish?

**Comment by kitling** [comment]
They already have a rather large list of (correct me if I'm wrong) 60+ chips, with datasheets for most of them. Not saying it's complete, but they're not even done with the ones that they have datasheets for, which is why I deleted the requests of "can this be supported?" Different matter entirely if those were already all done.

The main thing that needs to be done before this can be merged is to get back up to feature parity. Supporting ak2i and r4i gold once again. I may be able to work on that sometime later today.

A more minor thing that should be done is to avoid erasing every block, but at least I am not going to view it as a major blocker. It'll 'just' means that injection takes longer.

**Comment by DiamondMinerITA** [comment]
But how can i get the test version?
I want to help test it!

**Comment by eaSyRiideR** [comment]
Hello
I have an R4 SDHC Dual Core 2016.
What should I select/do exactly?
Which one is compatible with my card?

**Comment by annson24** [comment]
Test report on latest commit:

* AK2i works proprely now, generated hash on the backup is same as the one made on 0.1.3.
* DSTTs w/ flashchip of SPANSION MBM29LV400BC and ST M29W400B still doesn't get injected w/ ntrboot.

**Comment by annson24** [comment]
Edit: disregard my last report. That was on the commit 2hours ago. Will test again.

**Pull request merged**
