### PR TITLE
Add r4iGold (r4ids.cn) rev4-5 support

### PR DESCRIPTION
**Pull request by zoogie**
Copypasta inheritance is not what I hoped for. It does work at least. 
Tested on my rev5.

### CODE REVIEW

**Comment by zoogie** [comment]
1. already tried that
2. don't want to mess with the ui any

This is as far as I go with this. I was satisfied with my python stuff tbo.
If the PR isn't accepted I'm fine with letting this die here.

**Comment by d3m3vilurr** [comment]
@zoogie I made new pr about that. :)

**Comment by d3m3vilurr** [comment]
ah sorry, I was misunderstand about your comment. I meant just rev4/rev5 things. we need another detecting process for support rev6 and 7

**Comment by kitling** [comment]
I think it's safe to close this PR in favor of @d3m3vilurr's PR.

**Pull request closed without merging**
