### PR TITLE
 Move platform-independent parts of NTR card interface here

### PR DESCRIPTION
**Pull request by angelsl**
Still WIP: secure area reading, software Key2

### CODE REVIEW

**Comment by kitling** [comment]
Reiterating that I think we should remove the static class wrappers around the functions now in the platform and ntrcard namespace, but it lgtm besides that.

Wrapping the whole thing in a, say, flashcart_core namespace could also be nice, but not a priority.

**Comment by kitling** [comment]
Heck yeah. LGTM. @handsomematt how does this look to you?

**Comment by kitling** [comment]
Handsomematt said this looks good. Merging.

**Comment by d3m3vilurr** [comment]
@angelsl why you made OpFlags, and why not exist reserialize method?

**Pull request merged**
